### ISSUE TITLE
Icon list license and source.

### ISSUE THREAD

**Issue by 4l1fe** [JetBrains/ui#43]
I like the Jetbrains design and am curious if you are interested in publication your [icon list](https://jetbrains.design/intellij/resources/icons_list/) in the open-source library **iconify**  https://github.com/iconify/collections-json/issues/22 ?

They accumulate open source icons from other sources and provide a convenient api to reuse them.

**Comment by c5inco** [comment]
The icons license is Apache 2.0 (see [this closed issue](https://github.com/JetBrains/ui/issues/27#issuecomment-766708521) for more detail). 

For publishing to Iconify, we will discuss it based on our future plans for the icons. I'm not familiar with Iconify, but not sure if multi-colored SVG icons will be an issue with the service, since in my past experience this has been an issue to make this play with web frameworks.

**Comment by 4l1fe** [comment]
> For publishing to Iconify, we will discuss it based on our future plans for the icons

Ok, let people know what you decided.

> I'm not familiar with Iconify, but not sure if multi-colored SVG icons will be an issue with the service, since in my past experience this has been an issue to make this play with web frameworks.

I don't know either =)

Thx for the answer.

**Comment by bennetfabian** [comment]
@c5inco Any updates?
